#!/bin/bash

set -e 

mkdir -p /mnt/chroot

# mount btrfs
mount -o subvol=@ /dev/sda1 /mnt/chroot
mount -o subvol=@home /dev/sda1 /mnt/chroot/home
mount /dev/sdb1 /mnt/tmp/boot/efi
echo btrfs done

# mount fs APIs
cd /mnt/chroot
mount -t proc /proc /mnt/chroot/proc/
mount -t sysfs /sys /mnt/chroot/sys/
mount -o bind /dev /mnt/chroot/dev/
echo api done

# mount EFI vars
mount -o bind /sys/firmware/efi/efivars sys/firmware/efi/efivars/
echo efi vars done

# copy DNS config
cp /etc/resolv.conf etc/resolv.conf

# chroot
chroot /mnt/chroot /bin/bash

# source bash config
source /etc/profile
source ~/.bashrc
export PS1="(chroot) $PS1"

# validate fstab and crypttab
cat /etc/fstab
cat /etc/crypttab

# update initramfs
# update-initramfs -u

# reinstall grub
# grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
# Installing for x86_64-efi platform.
# grub-install: warning: EFI variables cannot be set on this system.
# grub-install: warning: You will have to complete the GRUB setup manually.
# Installation finished. No error reported.

# generate efibootmgr entry
# update-grub

# repair fs
# fsck /dev/sdb1

# unmount /boot and mount /boot/efi
# umount /dev/sdb1
# mount /dev/sdb1 /boot/efi

# reinstall grub on matching directory as working clean snapshot
# grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB

# update-grub

# final check
# fsck /deb/sdb1

# exit chroot and unmount
# exit
# umount --recursive /mnt
